version: "3.8"

services:
  client:
    build: ./packages/client
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:80
  server:
    build: ./packages/server
    volumes: 
      - ./:/usr/src/app
    ports:
      - 4000:80
