version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.5
jobs:
  lint-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install All Dependencies for Unit Testing
                command: yarn install --production=false
                environment:
                  NODE_ENV: development
            - run:
                name: Lint All the Packages
                command: yarn lerna run lint
                environment:
                  NODE_ENV: development
            - run:
                name: Test All the Packages
                command: yarn lerna run test:ci
                environment:
                  NODE_ENV: development
            - codecov/upload:
                file: packages/server/coverage/*.json
                flags: server
            - codecov/upload:
                file: packages/client/coverage/*.json
                flags: client
workflows:
  lint-test-and-build:
    jobs:
      - lint-and-test
