version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install All Dependencies for Unit Testing
                command: yarn install
                environment:
                  NODE_ENV: test
            - run:
                name: Lint All the Packages
                  command: lerna run -concurrency 1 --stream lint
                  environment:
                    NODE_ENV: test
            - run:
                name: Test All the Packages
                  command: lerna run -concurrency 1 --stream lint
                  environment:
                    NODE_ENV: test
workflows:
    test:
      jobs:
        - test
