version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: export NODE_ENV=test yarn install
            - run: lerna run -concurrency 1 --stream lint
            - run: lerna run -concurrency 1 --stream test
workflows:
    test:
      jobs:
        - test
